
#define ERROR_BUFFER_SIZE 100

enum token {
  /*0.*/ BEGIN, 
  /*1.*/ END, 
  /*2.*/ READ, 
  /*3.*/ WRITE, 
  /*4.*/ IF, 
  /*5.*/ THEN, 
  /*6.*/ ELSE, 
  /*7.*/ ENDIF, 
  /*8.*/ WHILE, 
  /*9.*/ ENDWHILE,
  /*10.*/ ID, 
  /*11.*/ INTLITERAL, 
  /*12.*/ FALSEOP, 
  /*13.*/ TRUEOP, 
  /*14.*/ NULLOP, 
  /*15.*/ LPAREN, 
  /*17.*/ RPAREN, 
  /*18.*/ SEMICOLON, 
  /*19.*/ COMMA, 
  /*20.*/ ASSIGNOP, 
  /*21.*/ PLUSOP, 
  /*22.*/ MINUSOP, 
  /*23.*/ MULTOP, 
  /*24.*/ DIVOP, 
  /*25.*/ NOTOP, 
  /*26.*/ LESSOP, 
  /*27.*/ LESSEQUALOP, 
  /*28.*/ GREATEROP, 
  /*29.*/ GREATEREQUALOP, 
  /*30.*/ EQUALOP, 
  /*31.*/ NOTEQUALOP, 
  /*32.*/ SCANEOF, 
  /*33.*/ ERROR
};
